apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
  labels:
    app: {{ .Release.Name }}
type: Opaque
data:
  {{- if .Values.secrets.eosPassword }}
  EOS_PASSWORD: {{ .Values.secrets.eosPassword | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.authSecretKey }}
  AUTH_SECRET_KEY: {{ .Values.secrets.authSecretKey | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.cvpToken }}
  EOS_CVP_TOKEN: {{ .Values.secrets.cvpToken | b64enc | quote }}
  {{- end }}
